version: '2'
services:
  web:
    build: .
    container_name: 'web_node'
    command: npm run watch
    volumes:
      - .:/usr/src/app
      - /usr/src/app  /node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - bs
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
    tty: false

  bs:
    image: ustwo/browser-sync
    command: start --server --files "*.css"
    volumes:
      - ./sandbox:/source
    ports:
#      - "3000:3000"
      - "3001:3001"

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos