version: '2'
services:
  web:
    build: .
    container_name: 'web_node'
    command: ./start-server.sh
    volumes:
      - .:/usr/src/app
      - /usr/src/app  /node_modules
    ports:
      - "8080:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
    tty: false

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos